version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
