version: '3'
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    env_file:
      - ../../.env
    ports:
      - "${DOZZLE_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
