version: '3'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - '${PORTAINER_PORT}:9000'
    # environment:
      # - ADMIN_PASS=${PORTAINER_ADMIN_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
